### PR TITLE
Add an uploadNew method to publish new items to the web store

### PR DESCRIPTION
**Pull request by switz**
Let me know if you have any questions or requests of things to change

### CODE REVIEW

**Comment by bfred-it** [comment]
Great! I didn’t know this was possible.

It should probably return the extension ID so later calls can be set up to update it.

**Comment by switz** [comment]
Awesome, glad to hear it.

It does, you can access the extension id from the “id” key of the object returned

**Comment by bfred-it** [comment]
Great. Hope to this change in the cli version too

**Comment by switz** [comment]
I should update the README docs as well.

**Comment by fregante** [comment]
Ping on this if you have time 🤗

**Comment by switz** [comment]
Sorry, don't really have the time at the moment. Feel free to take it over though!

**Pull request closed without merging**
